name: flatland-rl

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - psutil==5.7.2
  - pytorch==1.6.0
  - pip==20.2.3
  - python==3.6.8
  - networkx==2.5
  - pycairo==1.20.0
  - autopep8==1.5.4
  - tabulate==0.8.7
  - tqdm==4.51.0
  - wandb==0.10.11
  - pip:
      - -r file:conda_pip_requirements.txt
